version: "3"
services:
    web:
        image: todo/web
        build: .
        ports:
            - "4000:4000"
        environment:
            - DB=mongodb://mongo:27017/todo
        depends_on:
            - mongo
    mongo:
        image: mongo
        ports:
            - "27017:27017"
